name: Go Continuous Improvement
on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/**.go'
      - 'internal/**.go'
  pull_request:

jobs:
  go-pipeline:
    runs-on: ubuntu-latest
    container:
      image: golang
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run CI task from Taskfile
        run: task ci

      - name: Run end-2-end tests
        run: CRYPTO_BROKER_PROFILES_DIR=${GITHUB_WORKSPACE}/example-profiles go test -run E2E -race ./...

      - name: Run unit tests
        run: |
          CRYPTO_BROKER_PROFILES_DIR=${GITHUB_WORKSPACE}/example-profiles go test -skip E2E -covermode=count -coverpkg=./... -coverprofile cover.out -v ./...
          go tool cover -html cover.out -o cover.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cover.html
