name: 'Publish-GHCR'

# Everytime a new version tag is pushed
# or the workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag (used when not automatically triggered)"
        required: true
        default: "dev"
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# Sets the permissions granted to the `GITHUB_TOKEN` for the actions.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # Uses the `docker/login-action` action to log in to the Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/open-crypto-broker
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run image build and push pipeline
        uses: open-crypto-broker/.github/actions/publish-ghcr@main
        with:
          registry: ghcr.io/open-crypto-broker
          image_name: server
          image_tag: ${{ github.event.inputs.tag || github.ref_name }}
