#
name: Create and publish image to GHCR

# Everytime a new version tag is pushed
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Fallback tag (used when not triggered by a git tag)"
        required: true
        default: "dev"
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# environment variables for the workflow
env:
  REGISTRY: ghcr.io/open-crypto-broker
  IMAGE_NAME: server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # Uses the `docker/login-action` action to log in to the Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Extract metadata (tags, labels) for Docker (tag-variant)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: meta_tag
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
      #
      - name: Extract metadata (tags, labels) for Docker (manual trigger variant)
        if: github.event_name == 'workflow_dispatch'
        id: meta_input
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
      # build the image; if the build succeeds, it pushes the image to GitHub Packages,
      # using the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta_tag.outputs.tags || steps.meta_input.outputs.tags }}
          labels: ${{ steps.meta_tag.outputs.labels || steps.meta_input.outputs.labels }}

      # This step generates an artifact attestation for the image.
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

