name: Create-Release-Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 1.3.0)'
        required: true

permissions:
  contents: write

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    environment: DEPLOYMENT
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Use git-cliff for changelog generation, create git tag, push to repo
        uses: open-crypto-broker/.github/actions/git-cliff@main
        with:
          REF_NAME: ${{ github.ref_name }}
          VERSION: ${{ github.event.inputs.version }}
